//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccommodationModule
    {
        public int AccommodationModuleID { get; set; }
        public int AccommodationID { get; set; }
        public int ModuleID { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime Create_Date { get; set; }
    }
}
