//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssistiveTechnology
    {
        public int AssistiveTechnologyID { get; set; }
        public int IEPid { get; set; }
        public Nullable<bool> RequireAssistiveTechnology { get; set; }
        public string Description { get; set; }
        public System.DateTime Create_Date { get; set; }
    }
}
