//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccommodation
    {
        public int AccommodationID { get; set; }
        public int IEPid { get; set; }
        public string Description { get; set; }
        public string Frequency { get; set; }
        public string Duration { get; set; }
        public string LocationCode { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
        public int AccomType { get; set; }
        public Nullable<System.DateTime> AnticipatedStartDate { get; set; }
        public Nullable<System.DateTime> AnticipatedEndDate { get; set; }
        public string Location { get; set; }
        public bool Completed { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public string Module { get; set; }
    
        public virtual tblLocation tblLocation { get; set; }
    }
}
