//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArchiveEvaluationDate
    {
        public int archiveEvaluationDateID { get; set; }
        public int userID { get; set; }
        public System.DateTime evalutationDate { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    }
}
