//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArchiveIEPExit
    {
        public int tblArchiveIEPExitID { get; set; }
        public int userID { get; set; }
        public System.DateTime exitDate { get; set; }
        public string exitNotes { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public string USD { get; set; }
        public string BuildingID { get; set; }
        public string StatusCode { get; set; }
    }
}
