//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBuilding
    {
        public string BuildingID { get; set; }
        public string USD { get; set; }
        public string BuildingName { get; set; }
        public Nullable<int> Active { get; set; }
        public string Phone { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public string Address_Mailing { get; set; }
        public string Address_Physical { get; set; }
        public string State { get; set; }
        public bool isTest { get; set; }
        public int BuildingTypeID { get; set; }
        public bool isServiceOnly { get; set; }
    }
}
