//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblContingencyPlan
    {
        public int ContingencyPlanID { get; set; }
        public int IEPid { get; set; }
        public bool NoContingencyPlan { get; set; }
        public bool RemoteLearning_DistrictResponse { get; set; }
        public bool RemoteLearning_ParentRequest { get; set; }
        public string NatureProposedPlan { get; set; }
        public string Services { get; set; }
        public string Accommodations { get; set; }
        public string Goals { get; set; }
        public string OtherConsiderations { get; set; }
        public Nullable<bool> Completed { get; set; }
    }
}
