//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCalendarTemplate
    {
        public System.DateTime SchoolDate { get; set; }
        public bool NoService { get; set; }
        public bool canHaveClass { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public short SchoolYear { get; set; }
        public byte SchoolMonth { get; set; }
        public byte SchoolWeek { get; set; }
        public byte SchoolQuarter { get; set; }
    }
}
