//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntityLocation
    {
        public string LocationID { get; set; }
        public string USD { get; set; }
        public string BUildingID { get; set; }
        public string EntityID { get; set; }
        public string LocationName { get; set; }
        public bool Active { get; set; }
    }
}
