//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormTransportationRequest
    {
        public int FormTransportationRequestId { get; set; }
        public int StudentId { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string USD { get; set; }
        public string School { get; set; }
        public string Grade { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string ReceivingUSD { get; set; }
        public string TransportationDirector { get; set; }
        public string TransportationDirectorPhone { get; set; }
        public string ReceivingTeacherAndProgram { get; set; }
        public Nullable<System.DateTime> BeginDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> Hours { get; set; }
        public string Contact_1_Name { get; set; }
        public string Contact_1_HomePhone { get; set; }
        public string Contact_1_WorkPhone { get; set; }
        public string Contact_2_Name { get; set; }
        public string Contact_2_HomePhone { get; set; }
        public string Contact_2_WorkPhone { get; set; }
        public string BabySitterDaycareNameAndPhone { get; set; }
        public string HomeAddress { get; set; }
        public string FamilyPhysicianAndHosptial { get; set; }
        public string PickupLocation { get; set; }
        public string ReturnLocation { get; set; }
        public Nullable<bool> WheelChair { get; set; }
        public Nullable<bool> CarSeat { get; set; }
        public Nullable<bool> SeatBelt { get; set; }
        public Nullable<bool> ChestHarness { get; set; }
        public Nullable<bool> BusLift { get; set; }
        public Nullable<bool> BoosterSeat { get; set; }
        public Nullable<bool> Tray { get; set; }
        public Nullable<bool> PersonalCareAttendant { get; set; }
        public Nullable<bool> AdductorInPlace { get; set; }
        public Nullable<bool> Communication { get; set; }
        public Nullable<bool> Other { get; set; }
        public string Other_Desc { get; set; }
        public string Documentation { get; set; }
        public string PositioningAndHandling { get; set; }
        public string MeidicationAndSideEffects { get; set; }
        public string Equipment { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
