//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormIEPMeetingConsentToInvite_
    {
        public int FormIEPMeetingConsentToInvite_Id { get; set; }
        public int StudentId { get; set; }
        public string ParticipatingAgency { get; set; }
        public Nullable<bool> ProvideTransitionService { get; set; }
        public Nullable<bool> FurtherInformed { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
