//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormTransitionReferral
    {
        public int FormTransitionReferralID { get; set; }
        public int StudentId { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public string From_School { get; set; }
        public string From_Address { get; set; }
        public string From_Phone { get; set; }
        public string From_ResposibleLEAStaff { get; set; }
        public string To_LocalRegabilitationOffice { get; set; }
        public string To_Address { get; set; }
        public string To_Phone { get; set; }
        public string To_ATTN { get; set; }
        public string Student_Name { get; set; }
        public string Student_Address { get; set; }
        public string Student_Phone { get; set; }
        public string Student_DOB { get; set; }
        public string Student_ExitDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
