//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormChildOutcomes_SupportingEvidence
    {
        public int SupportingEvidenceId { get; set; }
        public int FormChildOutcomeID { get; set; }
        public string Question { get; set; }
        public string Source { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string SummaryOfResults { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    
        public virtual tblFormChildOutcome tblFormChildOutcome { get; set; }
    }
}
