//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormIEPTeamConsideration
    {
        public int FormIEPTeamConsiderationsId { get; set; }
        public int StudentId { get; set; }
        public Nullable<System.DateTime> IEPMeetingDate { get; set; }
        public string ChildsStrength { get; set; }
        public string UtilizeStrength { get; set; }
        public string ConcernsForEnhancing { get; set; }
        public string ConcernsAddressesd { get; set; }
        public string HarmfulEffects { get; set; }
        public string PhysicalEducatoin { get; set; }
        public string ExtendedSchoolYear { get; set; }
        public Nullable<bool> NeedsBeenConsidered_Yes { get; set; }
        public Nullable<bool> NeedsBeenConsidered_No { get; set; }
        public string NeedsBeenConsidered_Desc { get; set; }
        public Nullable<bool> BehaviorImpede_Yes { get; set; }
        public Nullable<bool> BehaviorImpede_No { get; set; }
        public string BehaviorImpede_Desc { get; set; }
        public Nullable<bool> InstructionInBraille_Yes { get; set; }
        public Nullable<bool> InstructionInBraille_No { get; set; }
        public string InstructionInBraille_Desc { get; set; }
        public Nullable<bool> LimitedEnglish_Yes { get; set; }
        public Nullable<bool> LimitedEnglish_No { get; set; }
        public string LimitedEnglish_Desc { get; set; }
        public Nullable<bool> CommunicationNeeds_Yes { get; set; }
        public Nullable<bool> CommunicationNeeds_No { get; set; }
        public string CommunicationNeeds_Desc { get; set; }
        public Nullable<bool> HearingCommunicationNeeds_Yes { get; set; }
        public Nullable<bool> HearingCommunicationNeeds_No { get; set; }
        public string HearingCommunicationNeeds_Desc { get; set; }
        public Nullable<bool> AssistiveTech_Yes { get; set; }
        public Nullable<bool> AssistiveTech_No { get; set; }
        public string AssistiveTech_Desc { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
