//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormArchive
    {
        public int FormArchiveID { get; set; }
        public int Student_UserID { get; set; }
        public int Creator_UserID { get; set; }
        public int IEPid { get; set; }
        public System.DateTime ArchiveDate { get; set; }
        public string FormName { get; set; }
        public byte[] FormFile { get; set; }
        public bool isUpload { get; set; }
    }
}
