//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormFileReview
    {
        public int FormFileReviewID { get; set; }
        public int StudentID { get; set; }
        public string USD { get; set; }
        public string StudentName { get; set; }
        public System.DateTime FormDate { get; set; }
        public Nullable<int> ParentRightsProvided { get; set; }
        public Nullable<int> AssessNotDiscrimatory { get; set; }
        public Nullable<int> AssessNativeLanguage { get; set; }
        public Nullable<int> AssessExceptionality { get; set; }
        public Nullable<int> PublicAgencyPayForDx { get; set; }
        public Nullable<int> QualifiedProfExceptionality { get; set; }
        public Nullable<int> GroupContainQualified { get; set; }
        public Nullable<int> NoSingleCriterionUsed { get; set; }
        public Nullable<int> CarefullyConsider { get; set; }
        public Nullable<int> NotDeterminant { get; set; }
        public Nullable<int> AcademicLevelDesc { get; set; }
        public Nullable<int> FunctionalLevelDesc { get; set; }
        public Nullable<int> DescribeAffects { get; set; }
        public Nullable<int> GoalsDesignedToMeet { get; set; }
        public Nullable<int> GoalsMeasurable { get; set; }
        public Nullable<int> GoalsProgress { get; set; }
        public Nullable<int> AlternativeAssessment { get; set; }
        public Nullable<int> IncludeProjectedDate { get; set; }
        public Nullable<int> IncludeServices { get; set; }
        public Nullable<int> EnhanceEducation { get; set; }
        public Nullable<int> PostiveBehavioralIntervention { get; set; }
        public Nullable<int> EnglishProficiency { get; set; }
        public Nullable<int> EducationalPlacement { get; set; }
        public Nullable<int> SeverityOfDisability { get; set; }
        public string Comments { get; set; }
        public int CreatedBy { get; set; }
        public int ModifiedBy { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
