//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFormPriorWritten_Ident
    {
        public int FormPriorWritten_IdentId { get; set; }
        public int StudentId { get; set; }
        public string ParentName { get; set; }
        public Nullable<System.DateTime> FormDate { get; set; }
        public Nullable<System.DateTime> MeetingDate { get; set; }
        public Nullable<bool> ChildSPEDEligible { get; set; }
        public Nullable<bool> SPEDNeeded { get; set; }
        public Nullable<bool> SPEDPlacement { get; set; }
        public Nullable<bool> ModificationsThatEnableSPED { get; set; }
        public Nullable<bool> Identification_Section { get; set; }
        public Nullable<bool> ChildIsEligible { get; set; }
        public Nullable<bool> ChildMeetsCriteria { get; set; }
        public Nullable<bool> SPEDNecessary { get; set; }
        public Nullable<bool> ChildNotElgible { get; set; }
        public Nullable<bool> ChildDoesNotMeetCriteria { get; set; }
        public Nullable<bool> SPEDNotNecessary { get; set; }
        public Nullable<bool> InitialServices_Section { get; set; }
        public Nullable<bool> ChangesInService_Section { get; set; }
        public Nullable<bool> ChangeInService { get; set; }
        public Nullable<bool> MaterialChangeInService { get; set; }
        public Nullable<bool> ChangeInPlacement_Section { get; set; }
        public Nullable<bool> ChangeInPlacements { get; set; }
        public Nullable<bool> SubstantialChangeInPlacement { get; set; }
        public Nullable<bool> OtherChanges { get; set; }
        public Nullable<bool> LEARefusesToChangeIdentification { get; set; }
        public string DescriptionOfAction { get; set; }
        public string ExplaninationWhy { get; set; }
        public string OptionsConsidered { get; set; }
        public string DescriptionOfData { get; set; }
        public string OtherFactors { get; set; }
        public string DeliveriedByWho { get; set; }
        public Nullable<bool> DelieveredByHand { get; set; }
        public Nullable<bool> DelieveredByMail { get; set; }
        public Nullable<bool> DelieveredByOther { get; set; }
        public string DelieveredByOtherDesc { get; set; }
        public string DeliveriedTo { get; set; }
        public Nullable<System.DateTime> DelieveredDate { get; set; }
        public string SchoolContact { get; set; }
        public string SchoolContactAddress { get; set; }
        public string SchoolContactPhone { get; set; }
        public Nullable<bool> GivenConsent { get; set; }
        public Nullable<bool> RefuseConsent { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
    }
}
