//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblIEPHealth
    {
        public int IEPHealthID { get; set; }
        public int IEPid { get; set; }
        public bool NoConcerns { get; set; }
        public bool Concerns { get; set; }
        public bool Diagnosis { get; set; }
        public bool Medications { get; set; }
        public System.DateTime HearingDate { get; set; }
        public int HearingResult { get; set; }
        public System.DateTime VisionDate { get; set; }
        public int VisionResult { get; set; }
        public bool VisionImparied { get; set; }
        public Nullable<bool> HearingImparied { get; set; }
        public string MedicationDescription { get; set; }
        public Nullable<bool> MedicaidEligible { get; set; }
        public string MedicaidID { get; set; }
        public Nullable<bool> HealthCarePlan { get; set; }
        public string AdditionalHealthInfo { get; set; }
        public bool ProgressTowardGenEd { get; set; }
        public string LevelOfPerformance { get; set; }
        public string AreaOfNeedDescription { get; set; }
        public Nullable<bool> AreaOfNeed { get; set; }
        public Nullable<bool> NeedMetByGoal { get; set; }
        public Nullable<bool> NeedMetByAccommodation { get; set; }
        public Nullable<bool> NeedMetByOther { get; set; }
        public string NeedMetByOtherDescription { get; set; }
        public string PLAAFP_Strengths { get; set; }
        public string PLAAFP_Concerns { get; set; }
        public bool Completed { get; set; }
    }
}
