//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblModule
    {
        public int ModuleID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleTable { get; set; }
        public bool Active { get; set; }
    }
}
