//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReferralInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblReferralInfo()
        {
            this.tblReferralRelationships = new HashSet<tblReferralRelationship>();
            this.tblReferralRequests = new HashSet<tblReferralRequest>();
        }
    
        public int ReferralID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleInitial { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public Nullable<long> KIDSID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public string County { get; set; }
        public string Race { get; set; }
        public string Ethicity { get; set; }
        public string StudentLanguage { get; set; }
        public string ParentLanguage { get; set; }
        public Nullable<int> Grade { get; set; }
        public string AssignedUSD { get; set; }
        public string ResponsibleBuildingID { get; set; }
        public string NeighborhoodBuildingID { get; set; }
        public Nullable<System.DateTime> InitialEvalConsentSigned { get; set; }
        public string ReferralNotes { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReferralRelationship> tblReferralRelationships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblReferralRequest> tblReferralRequests { get; set; }
    }
}
