//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblService
    {
        public int ServiceID { get; set; }
        public int IEPid { get; set; }
        public System.DateTime StartDate { get; set; }
        public string ServiceType { get; set; }
        public string ServiceDescription { get; set; }
        public int Frequency { get; set; }
        public int Duration { get; set; }
        public string Location { get; set; }
        public string Comments { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
