//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransition
    {
        public int TransitionID { get; set; }
        public int IEPid { get; set; }
        public string Assessment_Needs { get; set; }
        public string Assessment_Strengths { get; set; }
        public string Assessment_Prefrences { get; set; }
        public string Assessment_Interest { get; set; }
        public bool Services_Reviewed { get; set; }
        public bool Planning_Facilitate { get; set; }
        public bool Planning_Align { get; set; }
        public Nullable<int> Planning_GraduationMonth { get; set; }
        public Nullable<int> Planning_GraduationYear { get; set; }
        public string Planning_Completion { get; set; }
        public Nullable<int> Planning_Credits { get; set; }
        public bool Planning_BenefitKRS { get; set; }
        public string Planning_ParentIntials { get; set; }
        public bool Planning_ConsentPrior { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    }
}
