//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    
    public partial class up_ReportStudentsByBuilding_Result4
    {
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int UserID { get; set; }
        public string BuildingID { get; set; }
        public string BuildingName { get; set; }
        public string USD { get; set; }
        public string DistrictName { get; set; }
        public string ContactName { get; set; }
        public string Email { get; set; }
        public string AddressLine { get; set; }
        public string City { get; set; }
        public string StudentState { get; set; }
        public string Zip { get; set; }
    }
}
