//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_BuildingList
    {
        public string USD { get; set; }
        public string BuildingID { get; set; }
        public string CodeBuildingID { get; set; }
        public bool isServiceOnly { get; set; }
        public string BuildingName { get; set; }
    }
}
