//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_GoalExport
    {
        public string KIDSID { get; set; }
        public string AssignedUSD { get; set; }
        public string ServiceCode { get; set; }
        public int goalID { get; set; }
        public Nullable<System.DateTime> IEPStartDate { get; set; }
        public Nullable<System.DateTime> IEPEndDate { get; set; }
        public string AnnualGoal { get; set; }
        public string IepStatus { get; set; }
        public string ServiceType_Billable { get; set; }
        public string Location_Billable { get; set; }
        public string Service_Billable { get; set; }
        public bool isGBMedicaid { get; set; }
        public bool isTestDistrict { get; set; }
        public bool isTestUser { get; set; }
    }
}
