//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_StudentExport
    {
        public int StudentNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleInitital { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Gender { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string District { get; set; }
        public Nullable<bool> TransportationFlag { get; set; }
        public string KIDSID { get; set; }
        public string Active { get; set; }
        public string MedicaidBeneficiaryID { get; set; }
        public System.DateTime UserCreateDate { get; set; }
        public System.DateTime UserUpdateDate { get; set; }
        public string IepStatus { get; set; }
        public string ServiceType_Billable { get; set; }
        public string Location_Billable { get; set; }
        public string Service_Billable { get; set; }
        public bool isGBMedicaid { get; set; }
        public Nullable<System.DateTime> IEPStartDate { get; set; }
        public Nullable<System.DateTime> IEPEndDate { get; set; }
        public bool isTestDistrict { get; set; }
        public bool isTestUser { get; set; }
    }
}
