//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenBushIEP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class zArchive_Services
    {
        public int ID { get; set; }
        public string ArchiveCode { get; set; }
        public System.DateTime Archive_Date { get; set; }
        public int OriginalServiceID { get; set; }
        public Nullable<int> IEPid { get; set; }
        public Nullable<int> SchoolYear { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ServiceCode { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<byte> DaysPerWeek { get; set; }
        public Nullable<short> Minutes { get; set; }
        public Nullable<int> ProviderID { get; set; }
        public string LocationCode { get; set; }
        public Nullable<System.DateTime> FiledOn { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public string USD { get; set; }
        public string BuildingID { get; set; }
        public string ProvidedFor { get; set; }
        public System.DateTime Create_Date { get; set; }
        public System.DateTime Update_Date { get; set; }
    
        public virtual tblProvider tblProvider { get; set; }
    }
}
